name: reviewdog
on: pull_request
env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.TEST2 }}
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: Install linters
        run: go get golang.org/x/lint/golint
      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.TEST2 }}
        run: |
          reviewdog -reporter=github-pr-check
